(() => {

    //Space Ship Animation

    gsap.registerPlugin(ScrollTrigger);

    const space_ship = document.querySelectorAll(".space_ship");

    const tl = gsap.timeline({
        scrollTrigger: {
            trigger: '.animation_container',
            pin: true,
            markers: false,
            end: '100% 100%',
            scrub: true,
        },
    });


    //TIMELINE


    tl.to(space_ship, { scale: 0.5, y: '30vh', duration: 4 })
    tl.to(space_ship, { rotate: 360, duration: 3.5 });

    //when timeline is complete, hide the animation container
    tl.eventCallback("onComplete", function () {
        document.querySelector('.animation_container').style.display = "none";
    });

    //intro-box pop up when timeline is complete

    tl.eventCallback("onComplete", function () {
        document.querySelector('.intro-box').style.display = "block";
    }

    );


    //Variables
    const characterInfo = document.querySelector('#characters');
    const filmCon = document.querySelector('#film-con');
    const filmTemplate = document.querySelector('#film-template');
    const baseURL = `https://swapi.dev/api/`;

    const spinner = `<?xml version="1.0" encoding="utf-8"?>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="50" cy="50" r="0" fill="none" stroke="#e90c59" stroke-width="2">
      <animate attributeName="r" repeatCount="indefinite" dur="1s" values="0;40" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline" begin="0s"></animate>
      <animate attributeName="opacity" repeatCount="indefinite" dur="1s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline" begin="0s"></animate>
    </circle><circle cx="50" cy="50" r="0" fill="none" stroke="#46dff0" stroke-width="2">
      <animate attributeName="r" repeatCount="indefinite" dur="1s" values="0;40" keyTimes="0;1" keySplines="0 0.2 0.8 1" calcMode="spline" begin="-0.5s"></animate>
      <animate attributeName="opacity" repeatCount="indefinite" dur="1s" values="1;0" keyTimes="0;1" keySplines="0.2 0 0.8 1" calcMode="spline" begin="-0.5s"></animate>
    </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>`;
    
    let button = document.querySelector('#btn-start');
    let characterMenu = document.querySelector('#menu');
    let menubox = document.querySelector('.intro-box');
    


    //Functions

    //1st AJAX call
    function getPeople() {


        fetch(`${baseURL}people`)

            .then(response => response.json())

            .then(function (response) {
                const people = response.results;
                const ul = document.createElement('ul');

                people.forEach(character => {
                    const select = document.querySelector('#search');
                    const option = document.createElement('option');
                    option.value = character['name'];
                    option.innerHTML = character['name'];
                    select.appendChild(option);


                    const film = (character['films']);


                    if (film.length > 4) {
                        option.dataset.film = film[3]

                    } else {
                        option.dataset.film = film[0];
                    }
                });
            })

            .then(function () {
                let searchbutton = document.querySelector('#submit');
                searchbutton.addEventListener('click', getMovie);

            })

            .catch(error => {
                console.log(error);
            });
    };

    function getMovie(e) {
        filmCon.innerHTML=spinner;
        const searchValue = document.querySelector('#search option:checked');
        const filmID = searchValue.dataset.film;
        console.log("hey: " + filmID);

        const existingImage = document.querySelector('#characters li');
        const img = document.createElement('img');
        img.src = `images/${searchValue.value}.jpeg`;
        
        if (existingImage) {
            existingImage.parentNode.removeChild(existingImage);
        }
        const ul = document.createElement('ul');
        const li = document.createElement('li');

        li.appendChild(img);
        ul.appendChild(li);


        characterInfo.appendChild(ul);


        
        fetch(`${filmID}`)
            .then(response => response.json())
            .then(function (response) {
                filmCon.innerHTML = "";
                const template = document.importNode(filmTemplate.content, true);
                const filmBody = template.querySelector(".film-description");
                filmBody.innerHTML = response.opening_crawl;
                const filmTitle = template.querySelector(".filmTitle");
                filmTitle.innerHTML = response.title;

                const filmImage = template.querySelector(".filmImage");
                filmImage.src = `images/${response.title}.jpeg`;
                filmCon.appendChild(template);

            })

            .catch((error) => {
                console.log(error);
            });

    }

    //hide firstmenubox until start is clicked
    function hideMenu() {
        console.log('hide menu');
        menubox.style.display = "none";
    }

    // Show menubox when start is clicked
    function showMenu() {
        console.log('show menu');
        characterMenu.style.display = "block";
    }


    button.addEventListener('click', hideMenu);
    button.addEventListener('click', showMenu);

    getPeople();



})();